### ISSUE TITLE
Fix blurry thumbnails of Blog posts

### ISSUE THREAD

**Issue by Harsh-Kadiyan** [Harsh-Kadiyan/E4C-Code#1]
This image is a thumbnail of my blog post from outside (it's a little bit blurred)
![image](https://user-images.githubusercontent.com/72309871/140597733-45ecb8af-f633-4f69-af72-30e621cc025f.png)

but in reality, this image is high quality (1080p)

real image
![image](https://user-images.githubusercontent.com/72309871/140597866-d051bcd0-ec15-4211-8ea2-50fd876d51f0.png)

I don't know why it is blurred in thumbnails when the Image quality is great

**Comment by brownpanthera** [comment]
is it open cause I didn't find that thumbnail

**Comment by Harsh-Kadiyan** [comment]
because It was removed that time, sorry for that but I have again applied thumbnail, now you can see it @brownpanthera

**Comment by brownpanthera** [comment]
okay thanks, I will try to fix it

**Comment by Harsh-Kadiyan** [comment]
tip : if you want to find a particular word in this long code eg  `<div>`, `images` etc 
Click on the editor of the blogger anywhere and press `Ctrl + F` it will open a small search bar 😁 @brownpanthera

**Comment by Harsh-Kadiyan** [comment]
my all posts are like this but I don't like in this way can you change for this
![image](https://user-images.githubusercontent.com/72309871/140601179-120760e9-14f0-438e-b13d-56e543092780.png)

to this means I don't want cover photos for my posts I only want is text-based... 

![image](https://user-images.githubusercontent.com/72309871/140601284-e1f9e359-1f85-4b69-9025-a6f02ba26c31.png)


tip : I removed 
![image](https://user-images.githubusercontent.com/72309871/140601325-f4de5a54-9a8c-4474-b807-af49ded663b6.png)
from inspect element to remove cover thumbnails

**Comment by AbhinavMV** [comment]
Hi Harsh 
i have created a pull request for this issue 
you can merge it and the issue will be fixed
Let me know if there is any issue.

**Comment by Harsh-Kadiyan** [comment]
@AbhinavMV you are a legend I was literally stuck in this : problem solved

![image](https://user-images.githubusercontent.com/72309871/140602417-3f1fdd86-3e71-4303-a4d5-0cf3aa4fed2f.png)
 
bhai moj kardi aaj to, thank you so much for help 😘

**Comment by Harsh-Kadiyan** [comment]
@brownpanthera bro issue solved by @AbhinavMV so closing now special thanks to both of you
